### ISSUE TITLE
현재 `CacheIsolator`에서는 CAT을 끄는 configuration은 탐색하지 않음

### ISSUE THREAD

**Issue by isac322** [dcslab-snu/hybrid_iso#1]
### 문제 현상
현재 98ddff6d8 커밋 기준으로 `CacheIsolator`는 foreground:background의 LLC 비율만 configuration으로써 탐색할뿐 (예. 10:10, 12:8 등), cache partitioning을 아예 하지 않는 configuration은 탐색하지 않는다. 

### 현재 상태
관련 기능을 위해, 이전 configuration을 의미하는 `CacheIsolator::_prev_step`변수를 만들고, 이 변수의 값이 `None`인데 `weaken()`을 호출하였을때만 CAT을 끄도록 했지만, 잘 동작하지 않음

### 문제의 중요성
CAT을 끄는 configuration을 탐색하지 않으면, streamcluster같이 cache partitioning을 하지않는 경우에 성능향상이 있는 경우를 놓칠 수 있다.

**Comment by YoonsungNam** [comment]
여기서 말한 cache partitioning을 아예 하지 않는다는게 20:20으로 주는것과 같은 상황을 말하는 건지?

**Comment by isac322** [comment]
@YoonsungNam 
1. 네네 20:20맞아요.
2. 자세한건 #5 에 댓글달게요

**Comment by isac322** [comment]
현재 토의 상황:
꼭 CAT을 끄는 configuration을 search하지 않아도, 반복적인 configuration searching을 통해 그때그때 최적의 configuration을 찾을 수 있다면 (CAT을 껐을 때 서로가 나누어 가지는 비율) 꼭 끌 필요가 없다.
따라서 현재의 구현체가 그러한 configuration으로 가는지를 출력된 metric값을 통해 확인할 필요가 있다.
